[settings]
idiomatic_version_file_enable_tools = ["node"]
lockfile = true
experimental = true

[tools]
bat = "latest"
bun = "latest"
delta = "latest"
deno = "latest"
eza = "latest"
gh = "latest"
"npm:@antfu/ni" = "latest"
"npm:difit" = "latest"
"npm:yarn" = "latest"
pnpm = "latest"
ruby = "latest"
starship = "latest"
node = "24"
shfmt = "latest"
ripgrep = "latest"
"github:nushell/nushell" = "latest"
cargo-binstall = "latest"
"npm:@openai/codex" = "latest"
fd = "latest"
"gem:ruby-lsp" = "latest"
"npm:kill-port" = "latest"
"npm:@jetbrains/junie-cli" = "latest"
"github:skanehira/version-lsp" = "latest"
"npm:@google/gemini-cli" = "latest"
"github:carapace-sh/carapace-bin" = "latest"
xh = "latest"
"github:sevenc-nanashi/ccsum" = "latest"
"pipx:github/spec-kit" = "latest"
"npm:ntfy-me-mcp" = "latest"
