[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
bat = "latest"
bun = "latest"
delta = "latest"
eza = "latest"
gh = "latest"
"npm:@antfu/ni" = "latest"
"npm:difit" = "latest"
pnpm = "latest"
ruby = "latest"
starship = "latest"
node = "latest"
shfmt = "latest"
ripgrep = "latest"
"github:nushell/nushell" = "latest"
cargo-binstall = "latest"
"npm:@openai/codex" = "latest"
